export default {

  CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',

  PROFILES_RECIEVED: 'PROFILES_RECIEVED',
  PROFILE_CREATED: 'PROFILE_CREATED',

  BOOKMARKS_RECIEVED: 'BOOKMARKS_RECIEVED',
  
  PROFILE_SELECTED: 'PROFILE_SELECTED'

}
